implement linter (#2)
* added stricter golangci.yaml

* fixed linter issue and used proper linter file template

* added vscode settings

* added more build targets

* added changelog enforcement
---------

Co-authored-by: OverlayFox <s.koester@clipmyhorse.tv>

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -5,48 +5,55 @@ name: Go
 
 on:
   push:
-    branches: [ "main" ]
+    branches: ["main"]
   pull_request:
-    branches: [ "main" ]
+    branches: ["main"]
 
 jobs:
+  check-changelog:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: Check if CHANGELOG.md was updated
+        run: |
+          git fetch origin main
+          if ! git diff --name-only origin/main HEAD | grep -q '^CHANGELOG.md$'; then
+            echo "CHANGELOG.md was not updated compared to main. Please update the changelog."
+            exit 1
+          fi
+
   build:
     runs-on: ubuntu-latest
-    
     strategy:
       matrix:
-        go-version: [ '1.21', '1.22', '1.23' ]
+        go-version: ["1.21", "1.22", "1.23", "1.24", "1.25", "1.26"]
 
     steps:
-    - uses: actions/checkout@v4
-
-    - name: Set up Go ${{ matrix.go-version }}
-      uses: actions/setup-go@v5
-      with:
-        go-version: ${{ matrix.go-version }}
-
-    - name: Verify dependencies
-      run: |
-        go mod tidy
-        git diff --exit-code # Fails if go mod tidy changed anything
-
-    - name: Build
-      run: go build -v ./...
-
-    - name: Test with Race Detector
-      run: go test -race -v ./...
+      - uses: actions/checkout@v4
+      - name: Set up Go ${{ matrix.go-version }}
+        uses: actions/setup-go@v5
+        with:
+          go-version: ${{ matrix.go-version }}
+      - name: Verify dependencies
+        run: |
+          go mod tidy
+          git diff --exit-code # Fails if go mod tidy changed anything
+      - name: Build
+        run: go build -v ./...
+      - name: Test with Race Detector
+        run: go test -race -v ./...
 
   lint:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4
-    
-    - name: Set up Go
-      uses: actions/setup-go@v5
-      with:
-        go-version: '1.22'
-
-    - name: golangci-lint
-      uses: golangci/golangci-lint-action@v4
-      with:
-        version: latest
+      - uses: actions/checkout@v4
+      - name: Set up Go
+        uses: actions/setup-go@v5
+        with:
+          go-version: "1.22"
+      - name: golangci-lint
+        uses: golangci/golangci-lint-action@v9
+        with:
+          version: v2.11.3
